# Generated by Django 5.1.4 on 2025-01-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_label_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash_bin',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.label'),
        ),
    ]
