# Generated by Django 5.1.4 on 2025-01-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_note_conxtext_remove_note_title_note_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
